server.port: 7002
server.error.include-message: always


spring.data.mogodb:
    host: localhost
    port: 27017
    database: recommendation-db


logging:
    level:
        root: INFO
        com.marcotte: DEBUG
        org.springframwork.data.mongodb.core.MongoTemplate: DEBUG

---

spring.profiles: docker


spring.data.mongodb.host: mongodb


server.port: 8080