server.port: 7003
server.error.include-message: always



logging:
    level:
        root: INFO
        com.marcotte: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# recommend setting this to "none" in production env.
spring:
    jpa:
        hibernate:
            ddl-auto: update

spring.datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd

spring.datasource.hikari.initializationFailTimeout: 6000


---

spring.profiles: docker



spring.datasource:
    url: jdbc:mysql://mysql/review-db


server.port: 8080